apiVersion: v1
kind: Service
metadata:
  name: stream-server-loadbalancer
  labels:
    type: loadbalancer
    app-type: stream-server
    side: background
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app-id: conway-life-stream-server