apiVersion: v1
kind: Service
metadata:
  name: stream-server-service
  labels:
    type: service
    app-type: stream-server
    side: background
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app-id: conway-life-stream-server


