name: ci-cd

on:
  push:

jobs:
  build-test-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: set-up-jdk
        uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: cache-local-repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: grant-execute-permission-for-gradlew
        run: chmod +x gradlew
      - name: build-with-gradle
        run: ./gradlew build
#      - name: run-tests
#        run: ./gradlew scalatest
      - name: build-and-push-docker-image
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v1
        with:
          push: true
          dockerfile: docker/Dockerfile
          path: build/libs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fedormalyshkin/conway-life-stream-server
          tag_with_ref: true
          tag_with_sha: true
      - name: get-short-sha # https://github.community/t/substring-function/18401
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          id=$(echo ${{github.sha}} | cut -b-7)
          echo "::set-output name=sha::sha-$id"
        id: get-short-sha-id
      - name: set-k8s-context
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: rollup-update-k8s
        if: ${{ github.ref == 'refs/heads/master' }}
        run: kubectl set image deployment/stream-server-deployment conway-life-stream-server=fedormalyshkin/conway-life-stream-server:${{steps.get-short-sha-id.outputs.sha}}