name: ci-cd

on:
  push:

jobs:
  build-test-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: set-up-jdk
        uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: cache-local-repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: grant-execute-permission-for-gradlew
        run: chmod +x gradlew
      - name: build-with-gradle
        run: ./gradlew build
      - name: run-tests
        run: ./gradlew scalatest
      - name: login-to-docker-hub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set-up-docker-buildx
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/setup-buildx-action@v1
      - name: get-short-sha # https://github.community/t/substring-function/18401
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          id=$(echo ${{github.sha}} | cut -b-7)
          echo "::set-output name=sha::sha-$id"
        id: get-short-sha-id
      - name: build-and-push-docker-image
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile
          context: build/libs
          tags: |
            fedormalyshkin/conway-life-stream-server:latest
            fedormalyshkin/conway-life-stream-server:${{steps.get-short-sha-id.outputs.sha}}
      - name: set-k8s-context
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: rollup-update-k8s
        if: ${{ github.ref == 'refs/heads/master' }}
        run: kubectl set image deployment/stream-server-deployment conway-life-stream-server=fedormalyshkin/conway-life-stream-server:${{steps.get-short-sha-id.outputs.sha}}